### ISSUE TITLE
[META] Roadmap

### ISSUE THREAD

**Issue by krthr** [Cronun/cronun#1]
https://docs.google.com/document/d/1Pduhg6RghgcItgsMHOvlTm_v47Z9DZYQOBImLbDR7zE/edit

## CRONUN 2020-10 roadmap

- [ ] React app migration https://github.com/Cronun/cronun/issues/2
- [ ] Backend migration https://github.com/Cronun/cronun/issues/3
- [ ] Data mining https://github.com/Cronun/cronun/issues/4

### Meeting conclusions:
- **NO MIGRATION TO PHP for now (or never)**
