### ISSUE TITLE
[META]: Client migration

### ISSUE THREAD

**Issue by sjdonado** [Cronun/cronun#2]
- [x] Folder setup (TS and tailwindcss) https://github.com/Cronun/cronun/issues/5
- [x] GraphQL setup https://github.com/Cronun/cronun/issues/6
- [x] Merge landing and login page https://github.com/Cronun/cronun/issues/7
- [x] Redux setup https://github.com/Cronun/cronun/issues/8
- [ ] Cypress setup https://github.com/Cronun/cronun/issues/9
- [ ] System manual https://github.com/Cronun/cronun/issues/10

**Comment by sjdonado** [comment]
@rmacuna por fa, cuando tengas los mockups añadelos a la descripción

**Comment by rmacuna** [comment]
Correcto, pronto los tendré listos!

**Comment by rmacuna** [comment]
<img width="1440" alt="Cronun Home-1" src="https://user-images.githubusercontent.com/25620714/102838725-e6d46280-43cc-11eb-8d01-1aeeaf97c666.png">
<img width="1440" alt="Cronun Home-2" src="https://user-images.githubusercontent.com/25620714/102838729-e936bc80-43cc-11eb-8c37-4ea1abdd7fae.png">
<img width="1440" alt="Cronun Home-3" src="https://user-images.githubusercontent.com/25620714/102838734-ea67e980-43cc-11eb-9fe6-429af088d95e.png">
<img width="1440" alt="Cronun Home-4" src="https://user-images.githubusercontent.com/25620714/102838737-ea67e980-43cc-11eb-9b2c-07bf6d85cb9a.png">
<img width="1440" alt="Cronun Home-5" src="https://user-images.githubusercontent.com/25620714/102838738-eb008000-43cc-11eb-845d-4a3923c77762.png">
<img width="1440" alt="Cronun Home" src="https://user-images.githubusercontent.com/25620714/102838740-eb991680-43cc-11eb-8e69-d9b5da712dbd.png">

New mockups!
