### ISSUE TITLE
[META]: Backend migration

### ISSUE THREAD

**Issue by sjdonado** [Cronun/cronun#3]
- [x] NestJS setup
- [x] Generate tests
- [ ] Reduce database complexity (maybe use postgreSQL instead?)
- [ ] GraphQL migration
- [ ] System manual - Documentation (schema, folder structure, main services)

## Queries
- [ ] getConflictWeights
- [ ] ~getGroups~ Se usará Algolia
- [x] getGroup
- [x] getMultipleGroups
- [x] ~getSubjects~ Se usa Algolia para la búsqueda de materias
- [x] getSubjectGroups
- [ ] getProfessors
- [x] getProfessor
- [ ] getMySchedule
- [ ] userSchedules
- [x] getDepartments
- [x] getDepartment
